# Generated by Django 4.0.6 on 2022-12-10 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Instructor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instructor_name', models.CharField(max_length=64, verbose_name='老师名')),
                ('average_rate', models.IntegerField(verbose_name='评分')),
            ],
        ),
    ]
